import type { Project, GenerationResult, Stem } from "@/types/music";

const MOCK_PROJECTS: Project[] = [
  {
    id: "proj_1",
    title: "Cinematic Dawn",
    description: "Epic orchestral piece with Sri Lankan influences",
    coverArt: "/images/project-cinematic.jpg",
    bpm: 128,
    key: "C",
    scale: "major",
    timeSignature: { numerator: 4, denominator: 4 },
    duration: 240,
    tracks: [],
    createdAt: "2026-09-02T14:30:00Z",
    updatedAt: "2026-09-03T10:15:00Z",
    status: "completed",
    version: 3,
    versions: [],
    tags: ["cinematic", "orchestral", "sri-lankan"],
    modelUsed: "sam-ai-orchestra-v2",
  },
  {
    id: "proj_2",
    title: "Monsoon Nights",
    description: "Tamil pop ballad with electronic elements",
    coverArt: "/images/project-monsoon.jpg",
    bpm: 96,
    key: "Am",
    scale: "minor",
    timeSignature: { numerator: 4, denominator: 4 },
    duration: 180,
    tracks: [],
    createdAt: "2026-08-29T08:00:00Z",
    updatedAt: "2026-09-01T20:45:00Z",
    status: "mixing",
    version: 2,
    versions: [],
    tags: ["tamil", "pop", "ballad"],
    modelUsed: "sam-ai-melody-v3",
  },
  {
    id: "proj_3",
    title: "Urban Beats",
    description: "Modern hip-hop production",
    coverArt: "/images/project-urban.jpg",
    bpm: 140,
    key: "Dm",
    scale: "minor",
    timeSignature: { numerator: 4, denominator: 4 },
    duration: 150,
    tracks: [],
    createdAt: "2026-08-25T16:20:00Z",
    updatedAt: "2026-08-28T11:30:00Z",
    status: "draft",
    version: 5,
    versions: [],
    tags: ["hip-hop", "urban"],
    modelUsed: "sam-ai-bassline-v1",
  },
  {
    id: "proj_4",
    title: "Temple Echoes",
    description: "Traditional Sri Lankan music fusion",
    coverArt: "/images/project-temple.jpg",
    bpm: 85,
    key: "G",
    scale: "major",
    timeSignature: { numerator: 7, denominator: 8 },
    duration: 200,
    tracks: [],
    createdAt: "2026-08-20T09:15:00Z",
    updatedAt: "2026-08-22T18:00:00Z",
    status: "archived",
    version: 1,
    versions: [],
    tags: ["traditional", "fusion", "srilankan"],
    modelUsed: "sam-ai-orchestra-v2",
  },
  {
    id: "proj_5",
    title: "Digital Voyager",
    description: "Synthwave electronic composition",
    coverArt: "/images/project-synthwave.jpg",
    bpm: 115,
    key: "Em",
    scale: "minor",
    timeSignature: { numerator: 4, denominator: 4 },
    duration: 220,
    tracks: [],
    createdAt: "2026-08-15T12:00:00Z",
    updatedAt: "2026-08-17T14:20:00Z",
    status: "mastering",
    version: 4,
    versions: [],
    tags: ["synthwave", "electronic", "80s"],
    modelUsed: "sam-ai-melody-v3",
  },
];

const MOCK_GENERATIONS: GenerationResult[] = [
  {
    id: "gen_1",
    jobId: "job_001",
    audioUrl: "/audio/gen-preview-1.mp3",
    waveform: Array.from({ length: 128 }, () => 0.3 + Math.random() * 0.5),
    duration: 62,
    bpm: 128,
    key: "C",
    scale: "major",
    genre: "Cinematic",
    language: "English",
    model: "sam-ai-orchestra-v2",
    createdAt: "2026-09-03T10:15:00Z",
    metadata: { energy: 0.8, mood: "heroic", structure: "verse-chorus-bridge" },
  },
  {
    id: "gen_2",
    jobId: "job_002",
    audioUrl: "/audio/gen-preview-2.mp3",
    waveform: Array.from({ length: 128 }, () => 0.2 + Math.random() * 0.4),
    duration: 48,
    bpm: 96,
    key: "Am",
    scale: "minor",
    genre: "Tamil Pop",
    language: "Tamil",
    model: "sam-ai-melody-v3",
    createdAt: "2026-09-01T20:45:00Z",
    metadata: { energy: 0.6, mood: "romantic", structure: "verse-prechorus-chorus" },
  },
  {
    id: "gen_3",
    jobId: "job_003",
    audioUrl: "/audio/gen-preview-3.mp3",
    waveform: Array.from({ length: 128 }, () => 0.4 + Math.random() * 0.5),
    duration: 140,
    bpm: 140,
    key: "Dm",
    scale: "minor",
    genre: "Hip-Hop",
    language: "English",
    model: "sam-ai-bassline-v1",
    createdAt: "2026-08-28T11:30:00Z",
    metadata: { energy: 0.9, mood: "excited", structure: "verse-chorus" },
  },
  {
    id: "gen_4",
    jobId: "job_004",
    audioUrl: "/audio/gen-preview-4.mp3",
    waveform: Array.from({ length: 128 }, () => 0.1 + Math.random() * 0.3),
    duration: 96,
    bpm: 85,
    key: "G",
    scale: "major",
    genre: "World/Fusion",
    language: "Sinhala",
    model: "sam-ai-orchestra-v2",
    createdAt: "2026-08-22T18:00:00Z",
    metadata: { energy: 0.5, mood: "calm", structure: "theme-variation" },
  },
];

const MOCK_STEMS_DATA: Stem[] = [
  {
    id: "stem_1",
    jobId: "job_001",
    type: "vocals",
    name: "Vocals",
    audioUrl: "/audio/stem-vocals.mp3",
    waveform: Array.from({ length: 64 }, () => 0.5 + Math.random() * 0.3),
    duration: 62,
    bpm: 128,
    key: "C",
    volume: 0.9,
    muted: false,
    soloed: false,
  },
  {
    id: "stem_2",
    jobId: "job_001",
    type: "drums",
    name: "Drums",
    audioUrl: "/audio/stem-drums.mp3",
    waveform: Array.from({ length: 64 }, () => 0.6 + Math.random() * 0.3),
    duration: 62,
    bpm: 128,
    key: "C",
    volume: 0.85,
    muted: false,
    soloed: false,
  },
  {
    id: "stem_3",
    jobId: "job_001",
    type: "bass",
    name: "Bass",
    audioUrl: "/audio/stem-bass.mp3",
    waveform: Array.from({ length: 64 }, () => 0.4 + Math.random() * 0.4),
    duration: 62,
    bpm: 128,
    key: "C",
    volume: 0.8,
    muted: false,
    soloed: false,
  },
  {
    id: "stem_4",
    jobId: "job_001",
    type: "other",
    name: "Other Instruments",
    audioUrl: "/audio/stem-other.mp3",
    waveform: Array.from({ length: 64 }, () => 0.3 + Math.random() * 0.3),
    duration: 62,
    bpm: 128,
    key: "C",
    volume: 0.75,
    muted: false,
    soloed: false,
  },];

const MOCK_MODELS = [
  { id: "model_1", name: "SAM Orchestra v2", type: "music" as const, version: "2.1.0", size: 8.2, gpu: "8GB", status: "loaded" as const, performance: 0.92, quality: 0.95, lastUpdated: "2026-08-28" },
  { id: "model_2", name: "SAM Melody v3", type: "music" as const, version: "3.0.1", size: 4.5, gpu: "6GB", status: "loaded" as const, performance: 0.88, quality: 0.91, lastUpdated: "2026-08-30" },
  { id: "model_3", name: "SAM Bassline v1", type: "music" as const, version: "1.2.0", size: 2.8, gpu: "4GB", status: "unloaded" as const, performance: 0.75, quality: 0.85, lastUpdated: "2026-08-20" },
  { id: "model_4", name: "SAM Vocalist v4", type: "vocal" as const, version: "4.0.0", size: 12.5, gpu: "12GB", status: "loaded" as const, performance: 0.94, quality: 0.97, lastUpdated: "2026-09-01" },
  { id: "model_5", name: "SAM Demucs Pro", type: "stem" as const, version: "1.0.0", size: 6.0, gpu: "8GB", status: "loaded" as const, performance: 0.89, quality: 0.93, lastUpdated: "2026-08-25" },
  { id: "model_6", name: "SAM Lyrics v2", type: "lyrics" as const, version: "2.1.0", size: 0.3, gpu: "CPU", status: "loaded" as const, performance: 0.96, quality: 0.89, lastUpdated: "2026-08-29" },
];

const MOCK_DATASETS = [
  { id: "ds_1", name: "World Music Corpus", version: 3, items: [], qualityScore: 94, createdAt: "2026-08-15", stats: { totalItems: 15400, totalDuration: 864000, averageBpm: 118, keyDistribution: {}, genreDistribution: {}, languageDistribution: {} } },
  { id: "ds_2", name: "Orchestral Samples", version: 2, items: [], qualityScore: 91, createdAt: "2026-08-10", stats: { totalItems: 8700, totalDuration: 432000, averageBpm: 72, keyDistribution: {}, genreDistribution: {}, languageDistribution: {} } },
  { id: "ds_3", name: "Vocal Dataset", version: 5, items: [], qualityScore: 88, createdAt: "2026-08-20", stats: { totalItems: 22300, totalDuration: 936000, averageBpm: 95, keyDistribution: {}, genreDistribution: {}, languageDistribution: {} } },
];

const MOCK_EXPERIMENTS = [
  { id: "exp_1", name: "Orchestra Final Training", datasetId: "ds_2", modelId: "model_1", batchSize: 16, learningRate: 0.0003, epochs: 50, steps: 12500, status: "completed" as const, loss: 0.045, gpuUtilization: 87, vram: 7.2, lossHistory: [0.5, 0.3, 0.2, 0.15, 0.1, 0.08, 0.06, 0.05, 0.045], eta: "Done", createdAt: "2026-09-01T08:00:00Z" },
  { id: "exp_2", name: "Vocal Voice Clone", datasetId: "ds_3", modelId: "model_4", batchSize: 8, learningRate: 0.0001, epochs: 30, steps: 8200, status: "running" as const, loss: 0.087, gpuUtilization: 92, vram: 10.1, lossHistory: [0.6, 0.45, 0.32, 0.25, 0.18, 0.12, 0.095, 0.087], eta: "2h 15m", createdAt: "2026-09-03T14:00:00Z" },
];

class MockDataService {
  getProjects() { return MOCK_PROJECTS; }
  getProject(id: string) { return MOCK_PROJECTS.find((p) => p.id === id) || MOCK_PROJECTS[0]; }
  getGenerations() { return MOCK_GENERATIONS; }
  getStems() { return MOCK_STEMS_DATA; }
  getVoices() { return []; }
  getModels() { return MOCK_MODELS; }
  getDatasets() { return MOCK_DATASETS; }
  getExperiments() { return MOCK_EXPERIMENTS; }
  getSystemMetrics() {
    return {
      cpu: 42,
      ram: { used: 12.4, total: 32 },
      gpu: { utilization: 78, vram: { used: 6.2, total: 8 }, temperature: 67 },
      storage: { used: 482, total: 2048 },
      workers: 4,
      queue: 2,
      activeJobs: 1,
    };
  }
}

export const mockDataService = new MockDataService();
export { MOCK_PROJECTS, MOCK_GENERATIONS, MOCK_STEMS_DATA, MOCK_MODELS, MOCK_DATASETS, MOCK_EXPERIMENTS };
