<?php
// =========================================================================
// SAM AI - Standalone Service Homepage Template
// Customize this per service by changing config.php
// =========================================================================
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/includes/auth-check.php';

$user = null;
$credit_balance = 0;

if ($session->isLoggedIn()) {
    $user = $session->getUser();
    $api->setToken($session->getToken());
    $balance_result = $api->getCreditBalance();
    if ($balance_result['status'] === 'success') {
        $credit_balance = $balance_result['data']['balance'] ?? 0;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo SITE_TITLE; ?></title>
    <meta name="description" content="<?php echo SITE_TAGLINE; ?>">
    <link rel="icon" href="favicon.ico">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/service.css">
    <style>
        :root {
            --theme: <?php echo THEME_COLOR; ?>;
            --theme-hover: <?php echo THEME_COLOR_HOVER; ?>;
        }
    </style>
</head>
<body>
    <?php include 'includes/header.php'; ?>

    <main class="hero-section">
        <div class="container">
            <h1><?php echo SITE_TAGLINE; ?></h1>
            <p class="subtitle">Powered by <a href="https://samai.com">SAM AI</a></p>

            <?php if ($session->isLoggedIn()): ?>
                <div class="credit-badge">
                    You have <strong><?php echo formatCredits($credit_balance); ?> credits</strong> available
                </div>
            <?php else: ?>
                <div class="hero-buttons">
                    <a href="register.php" class="btn btn-primary">Get Started — Sign Up</a>
                    <a href="login.php" class="btn btn-secondary">Already have an account?</a>
                </div>
            <?php endif; ?>
        </div>
    </main>

    <section class="features-section">
        <div class="container">
            <h2>Super App Features</h2>
            <div class="features-grid">
                <div class="feature-card">
                    <h3>⌨️ AI Keyboard & Typing</h3>
                    <p>Smart Sinhala, Tamil, and English AI-powered typing and translation tool.</p>
                </div>
                <div class="feature-card">
                    <h3>📰 AI Esana News</h3>
                    <p>Real-time breaking news summarized and generated by AI for Sri Lanka.</p>
                </div>
                <div class="feature-card">
                    <h3>🎙️ AI Voice & Radio</h3>
                    <p>Voice typing and AI-generated local radio stations in multiple languages.</p>
                </div>
                <div class="feature-card">
                    <h3>💳 Reload & Services</h3>
                    <p>Digital payments, reloads, and astrology services integrated into one platform.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="pricing-preview">
        <div class="container">
            <h2>How It Works</h2>
            <div class="steps">
                <div class="step">
                    <div class="step-num">1</div>
                    <h4>Sign Up</h4>
                    <p>Create an account in seconds.</p>
                </div>
                <div class="step">
                    <div class="step-num">2</div>
                    <h4>Purchase Credits</h4>
                    <p>Buy a credit pack starting at $5.</p>
                </div>
                <div class="step">
                    <div class="step-num">3</div>
                    <h4>Use the AI</h4>
                    <p>Each action deducts a small number of credits.</p>
                </div>
            </div>
            <a href="register.php" class="btn btn-primary">Start Now</a>
        </div>
    </section>

    <?php include 'includes/footer.php'; ?>
</body>
</html>
